# Generated by Django 5.1.4 on 2025-01-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(blank=True, max_length=11)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
