# Generated by Django 5.1.4 on 2025-01-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
