# Generated by Django 5.1.4 on 2025-01-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_rename_first_name_product_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phonenumber',
            field=models.IntegerField(blank=True),
        ),
    ]
