# Generated by Django 5.1.6 on 2025-05-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_alter_product_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
