# Generated by Django 5.1.6 on 2025-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='image/d3d4c2c0-8976-4c9f-888e-3e548d0fca14-PhotoRoom.png-PhotoRoom.png', null=True, upload_to='images'),
        ),
    ]
